answers = [
    {"answer": "Insatisfatório"},
    {"answer": "Pouco satisfatório"},
    {"answer": "Sem condições para responder"},
    {"answer": "Satisfatório"},
    {"answer": "Muito satisfatório"},
    {"answer": "Insegurança em atuar na área de formação"},
    {"answer": "Salário melhor em outra área"},
    {"answer": "Falta de oportunidade profissional"},
    {"answer": "Estou empregado"},
    {"answer": "Home office"},
    {"answer": "Híbrido"},
    {"answer": "Presencial"},
    {"answer": "Criatividade"},
    {"answer": "Iniciativa"},
    {"answer": "Interesse em novas tecnologias"},
    {"answer": "Adaptabilidade"},
    {"answer": "Interesse em se desenvolver"},
    {"answer": "Planejamento"},
    {"answer": "Comunicação"},
    {"answer": "Facilidade para trabalhar em equipe"},
    {"answer": "TCC"},
    {"answer": "Qualificação dos professores"},
    {"answer": "Metodologia de ensino"},
    {"answer": "Atividades práticas"},
    {"answer": "Projetos de extensão"},
    {"answer": "Eventos"},
    {"answer": "Estágio Obrigatório"},
    {"answer": "Currículo do curso"},
    {"answer": "Outros (descrever)"},
]
