answers = [
    {"answer": "Insatisfatório"},
    {"answer": "Pouco satisfatório"},
    {"answer": "Sem condições para responder"},
    {"answer": "Satisfatório"},
    {"answer": "Muito satisfatório"},
    {"answer": "Insegurança em atuar na área de fromação"},
    {"answer": "Salário melhor em outra área"},
    {"answer": "Falta de oportunidade profissional"},
    {"answer": "Estou empregado"},
    {"answer": "Outros (descrever)"},
    {"answer": "Home office"},
    {"answer": "Híbrido"},
    {"answer": "Criatividade"},
    {"answer": "Interesse em novas tecnologias"},
    {"answer": "Adaptabilidade"},
    {"answer": "Interesse em se desenvolver"},
    {"answer": "Planejamento"},
    {"answer": "Comunicação"},
    {"answer": "Facilidade para trabalhar em equipe"},
    
]
