repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: end-of-file-fixer
  - id: check-ast
  - id: check-toml
  - id: debug-statements
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.0
  hooks:
  - id: bandit
    args: ['-x', 'test', '-s', 'B701']
- repo: https://github.com/commitizen-tools/commitizen
  rev: master
  hooks:
  - id: commitizen
    stages: [commit-msg]
