"""alter_tables_ListJobsArea_JobsArea_add_relations

Revision ID: 057652eb3d0a
Revises: 40d5410b6eda
Create Date: 2022-10-17 15:37:29.723798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '057652eb3d0a'
down_revision = '40d5410b6eda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'listjobsarea', 'jobsarea', ['jobs_area_uuid'], ['uuid'])
    op.create_foreign_key(None, 'listjobsarea', 'students', ['student_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listjobsarea', type_='foreignkey')
    op.drop_constraint(None, 'listjobsarea', type_='foreignkey')
    # ### end Alembic commands ###
