"""torna_dados_pre_populados_unique

Revision ID: 08794e78ddd0
Revises: 5a5acc802e34
Create Date: 2023-08-03 17:36:49.400394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08794e78ddd0'
down_revision = '5a5acc802e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'answers', ['answer'])
    op.create_unique_constraint(None, 'employercharacteristics', ['characteristc'])
    op.create_unique_constraint(None, 'fieldactivity', ['activity'])
    op.create_unique_constraint(None, 'hiringproblems', ['problem'])
    op.create_unique_constraint(None, 'jobsarea', ['name'])
    op.create_unique_constraint(None, 'jobsprofile', ['name'])
    op.create_unique_constraint(None, 'previouslyjob', ['name'])
    op.create_unique_constraint(None, 'questions', ['questions'])
    op.create_unique_constraint(None, 'role', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("role_name_key", 'role', type_='unique')
    op.drop_constraint("questions_questions_key", 'questions', type_='unique')
    op.drop_constraint("previouslyjob_name_key", 'previouslyjob', type_='unique')
    op.drop_constraint("jobsprofile_name_key", 'jobsprofile', type_='unique')
    op.drop_constraint("jobsarea_name_key", 'jobsarea', type_='unique')
    op.drop_constraint("hiringproblems_problem_key", 'hiringproblems', type_='unique')
    op.drop_constraint("fieldactivity_activity_key", 'fieldactivity', type_='unique')
    op.drop_constraint("employercharacteristics_characteristc_key", 'employercharacteristics', type_='unique')
    op.drop_constraint("answers_answer_key", 'answers', type_='unique')
    # ### end Alembic commands ###
