"""create_relation_Company_User

Revision ID: 153f91c43f48
Revises: 720ff909380e
Create Date: 2022-09-21 15:11:25.575332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '153f91c43f48'
down_revision = '720ff909380e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'company', 'user', ['user_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.drop_column('company', 'user_uuid')
    # ### end Alembic commands ###
