"""troca Int para Float e Datatime para String

Revision ID: 1857cc2d7c3e
Revises: 9c99a9587cf0
Create Date: 2023-02-08 14:04:30.145260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1857cc2d7c3e'
down_revision = '9c99a9587cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'opening_hours',
               existing_type=postgresql.TIMESTAMP(), type_=postgresql.VARCHAR(255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'opening_hours',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
