"""turn_roleuuid_nullableFalse

Revision ID: 2014f2c2e03e
Revises: c2b116d5e36b
Create Date: 2022-10-14 13:50:57.698553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2014f2c2e03e'
down_revision = 'c2b116d5e36b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role_uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role_uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
