"""add_campusuuid_Courses_anda_remove_courseuuid_table_Campus

Revision ID: 235c80900183
Revises: d0c5d01ace96
Create Date: 2022-10-11 14:43:46.922036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '235c80900183'
down_revision = 'd0c5d01ace96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('campus_uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'courses', 'campus', ['campus_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'campus_uuid')
    # ### end Alembic commands ###
