"""create_relation_Student_AcademicProfile

Revision ID: 3973cc2176f2
Revises: e155cb409314
Create Date: 2022-10-03 17:41:25.840737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3973cc2176f2'
down_revision = 'e155cb409314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('academic_uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'students', 'academicprofiles', ['academic_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'academic_uuid')
    # ### end Alembic commands ###
