"""sobe_funcao_de_pop_db_init

Revision ID: 3999274ba3c8
Revises: 7b62c75d6698
Create Date: 2023-06-21 14:30:21.619051

"""
from alembic import op
import sqlalchemy as sa

from app import database

# revision identifiers, used by Alembic.
revision = '3999274ba3c8'
down_revision = '7b62c75d6698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    database.pop_db_init()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
