"""add_others_table_ListJobsArea

Revision ID: 3ce2db584f9a
Revises: 057652eb3d0a
Create Date: 2022-10-17 15:42:30.270157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce2db584f9a'
down_revision = '057652eb3d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listjobsarea', sa.Column('others', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listjobsarea', 'others')
    # ### end Alembic commands ###
