"""alter_answersuuid_False_to_True

Revision ID: 40d5410b6eda
Revises: 7bc2c8b17b51
Create Date: 2022-10-14 17:18:32.351449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '40d5410b6eda'
down_revision = '7bc2c8b17b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz', 'answers_uuid',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz', 'answers_uuid',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
