"""add_foreignkey_table_BranchOffice

Revision ID: 47c5ea221fe0
Revises: 2014f2c2e03e
Create Date: 2022-10-14 15:01:47.714366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47c5ea221fe0'
down_revision = '2014f2c2e03e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'branchoffice', 'address', ['address_uuid'], ['uuid'])
    op.create_foreign_key(None, 'branchoffice', 'company', ['company_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'branchoffice', type_='foreignkey')
    op.drop_constraint(None, 'branchoffice', type_='foreignkey')
    # ### end Alembic commands ###
