"""pop_init_db

Revision ID: 4d0fd7d91862
Revises: bd64a3d68f22
Create Date: 2023-06-22 16:55:54.049381

"""
from alembic import op
import sqlalchemy as sa

from app import database

# revision identifiers, used by Alembic.
revision = '4d0fd7d91862'
down_revision = 'bd64a3d68f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    database.pop_db_init()
    database.pop_db()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

