"""config_ForegeinKey_table_CoursesPCD

Revision ID: 5946d3d454fb
Revises: fb8cc60a7ec6
Create Date: 2022-10-11 17:12:20.767231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5946d3d454fb'
down_revision = 'fb8cc60a7ec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'coursespcd', 'courses', ['courses_uuid'], ['uuid'])
    op.create_foreign_key(None, 'coursespcd', 'pcd', ['pcd_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coursespcd', type_='foreignkey')
    op.drop_constraint(None, 'coursespcd', type_='foreignkey')
    # ### end Alembic commands ###
