"""add gender in Students table

Revision ID: 698ba6443ce9
Revises: a2748330785b
Create Date: 2023-03-30 15:50:25.996751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698ba6443ce9'
down_revision = 'a2748330785b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('gender', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'gender')
    # ### end Alembic commands ###
