"""teste_pre_pop

Revision ID: 7b62c75d6698
Revises: ee47aa5d099c
Create Date: 2023-06-20 15:09:23.022675

"""
from alembic import op
import sqlalchemy as sa

from app import database

# revision identifiers, used by Alembic.
revision = '7b62c75d6698'
down_revision = 'ee47aa5d099c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    database.pop_db_init()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
