"""add_others_table_Quiz

Revision ID: 7bc2c8b17b51
Revises: 47c5ea221fe0
Create Date: 2022-10-14 17:04:24.581647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc2c8b17b51'
down_revision = '47c5ea221fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('others', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz', 'others')
    # ### end Alembic commands ###
