"""alter_table_Quiz

Revision ID: 7d655f8a3e9e
Revises: 3973cc2176f2
Create Date: 2022-10-04 15:52:44.790661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d655f8a3e9e'
down_revision = '3973cc2176f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('students_uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('quiz', sa.Column('questions_uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('quiz', sa.Column('answers_uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'quiz', 'answers', ['answers_uuid'], ['uuid'])
    op.create_foreign_key(None, 'quiz', 'questions', ['questions_uuid'], ['uuid'])
    op.create_foreign_key(None, 'quiz', 'students', ['students_uuid'], ['uuid'])
    op.drop_column('quiz', 'question_uuid')
    op.drop_column('quiz', 'student_uuid')
    op.drop_column('quiz', 'answer_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('answer_uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('quiz', sa.Column('student_uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('quiz', sa.Column('question_uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'quiz', type_='foreignkey')
    op.drop_constraint(None, 'quiz', type_='foreignkey')
    op.drop_constraint(None, 'quiz', type_='foreignkey')
    op.drop_column('quiz', 'answers_uuid')
    op.drop_column('quiz', 'questions_uuid')
    op.drop_column('quiz', 'students_uuid')
    # ### end Alembic commands ###
