"""alter_tables_Lits

Revision ID: 9c99a9587cf0
Revises: a83c59bd8951
Create Date: 2022-10-19 11:33:54.182876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c99a9587cf0'
down_revision = 'a83c59bd8951'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('hiring', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'companypcd', 'pcd', ['pcd_uuid'], ['uuid'])
    op.create_foreign_key(None, 'companypcd', 'company', ['company_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companypcd', type_='foreignkey')
    op.drop_constraint(None, 'companypcd', type_='foreignkey')
    op.drop_column('company', 'hiring')
    # ### end Alembic commands ###
