"""adiciona number_children em Students e remove academic_coefficiente de AcademicProfiles

Revision ID: 9d959acb2124
Revises: 698ba6443ce9
Create Date: 2023-03-30 16:31:09.751508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d959acb2124'
down_revision = '698ba6443ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('number_children', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'number_children')
    # ### end Alembic commands ###
