"""altera column birthdate de Datetime para String

Revision ID: a2748330785b
Revises: cb1e3a2fdcf5
Create Date: 2023-02-08 15:21:15.564515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a2748330785b"
down_revision = "cb1e3a2fdcf5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "students",
        "birthdate",
        existing_type=postgresql.TIMESTAMP(),
        type_=postgresql.VARCHAR(255),
    )
    op.alter_column(
        "academicprofiles",
        "academic_coefficient",
        existing_type=postgresql.INTEGER(),
        type_=postgresql.FLOAT(),
    )
    op.alter_column(
        "courses",
        "employability_index",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "courses",
        "businessperson_index",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "courses",
        "public_server_index",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "courses",
        "public_server_index",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "courses",
        "businessperson_index",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "courses",
        "employability_index",
        existing_type=postgresql.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    # ### end Alembic commands ###
