"""add_ForeignKey_adn_relations_table_StudentsPcd

Revision ID: a83c59bd8951
Revises: e09852cc712d
Create Date: 2022-10-18 14:19:02.940772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a83c59bd8951'
down_revision = 'e09852cc712d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'studentspcd', 'students', ['students_uuid'], ['uuid'])
    op.create_foreign_key(None, 'studentspcd', 'pcd', ['pcd_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'studentspcd', type_='foreignkey')
    op.drop_constraint(None, 'studentspcd', type_='foreignkey')
    # ### end Alembic commands ###
