"""alter_foreignkey_table_Company

Revision ID: c2b116d5e36b
Revises: 2239ff61dd5f
Create Date: 2022-10-13 16:55:19.554162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b116d5e36b'
down_revision = '2239ff61dd5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('company_address_uuid_fkey', 'company', type_='foreignkey')
    op.create_foreign_key(None, 'company', 'address', ['address_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.create_foreign_key('company_address_uuid_fkey', 'company', 'user', ['address_uuid'], ['uuid'])
    # ### end Alembic commands ###
