"""add_lazy_in_table_Students

Revision ID: d0c5d01ace96
Revises: 7d655f8a3e9e
Create Date: 2022-10-04 17:21:22.154923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c5d01ace96'
down_revision = '7d655f8a3e9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
