"""add_in_Lists_tables

Revision ID: e09852cc712d
Revises: ad3eff9a8fc6
Create Date: 2022-10-17 17:14:13.314549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e09852cc712d'
down_revision = 'ad3eff9a8fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listcharacteristics', sa.Column('others', sa.String(length=255), nullable=True))
    op.add_column('listfieldactivities', sa.Column('others', sa.String(length=255), nullable=True))
    op.add_column('listhiringproblems', sa.Column('others', sa.String(length=255), nullable=True))
    op.add_column('listjobprofile', sa.Column('others', sa.String(length=255), nullable=True))
    op.add_column('listpreviouslyjobs', sa.Column('others', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listpreviouslyjobs', 'others')
    op.drop_column('listjobprofile', 'others')
    op.drop_column('listhiringproblems', 'others')
    op.drop_column('listfieldactivities', 'others')
    op.drop_column('listcharacteristics', 'others')
    # ### end Alembic commands ###
