"""add_CEP_in_table_Address

Revision ID: e155cb409314
Revises: ede6de06cb17
Create Date: 2022-10-03 15:13:40.736704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e155cb409314'
down_revision = 'ede6de06cb17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('cep', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'cep')
    # ### end Alembic commands ###
