"""altera column opening_hours de Datetime para String

Revision ID: e1c7e4a709a6
Revises: 1857cc2d7c3e
Create Date: 2023-02-08 15:07:55.985561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'e1c7e4a709a6'
down_revision = '1857cc2d7c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'opening_hours',
               existing_type=postgresql.TIMESTAMP(), type_=postgresql.VARCHAR(255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'opening_hours',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###