"""add_relation_table_Address_Students

Revision ID: ede6de06cb17
Revises: 22b42edf773a
Create Date: 2022-09-28 14:32:28.999733

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ede6de06cb17'
down_revision = '22b42edf773a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('address_uuid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'students', 'address', ['address_uuid'], ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'address_uuid')
    # ### end Alembic commands ###
