"""adiciona curriculum na table Students

Revision ID: ee47aa5d099c
Revises: 9d959acb2124
Create Date: 2023-03-30 16:41:31.646066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee47aa5d099c'
down_revision = '9d959acb2124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('curriculum', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'curriculum')
    # ### end Alembic commands ###
