"""alter_atribute_addressuuid_table_Campus

Revision ID: fb8cc60a7ec6
Revises: 235c80900183
Create Date: 2022-10-11 15:18:30.575391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb8cc60a7ec6'
down_revision = '235c80900183'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'campus', 'address', ['address_uuid'], ['uuid'])
    op.drop_column('campus', 'course_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campus', sa.Column('course_uuid', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'campus', type_='foreignkey')
    # ### end Alembic commands ###
